#!/usr/bin/env bash
# displays information about subdomains
# shellcheck disable=SC2086
domain=$1
subdomain=$2
func() {
	if (( $# == 2 ))
	then
		echo $0
		IP=$( dig $subdomain.$DOMAIN  | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | head -1 )
		REC=$( dig $subdomain.$DOMAIN | grep -A1 'ANSWER SECTION:' | tail -1 | cut -f4 )
		echo "The subdomain $subdomain is a $REC record and points to $IP"
	fi
}
func "$domain" "$subdomain"
