#!/usr/bin/env bash
# installs and configures a nginx server with http header
#shellcheck disable=SC2154
apt update;
apt-get install nginx -y;
service nginx start;
header="add_header X-Served-By $(hostname);";
sed -i "24i $header" /etc/nginx/sites-enabled/default;
service nginx reload;
