#!/usr/bin/env bash
# installs and configures a nginx server with http header
#shellcheck disable=SC2154
apt update;
apt-get install nginx -y;
service nginx start;
header="add_header X-Served-By $HOSTNAME;";
sed -i "16i $header;" /etc/nginx/nginx.conf
service nginx reload;
