#!/usr/bin/env bash
# runs nginx as non root
pkill apache2
service nginx stop
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sed -i "1i user nginx;" /etc/nginx/nginx.conf
echo "nginx ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nginx
service nginx restart
